name: terraform deploy

on:
  push:
    branches: [ infrastructureAsCode ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv -p python3.7 venv
        . ./venv/bin/activate
        mkdir python
        pip3 install -r requirements.txt -t ./python/
        mv meta/* ./python/
        zip -r layer.zip ./python > /dev/null
    - name: plan it
      env:
        AWS_ACCESS_KEY_ID: {{ secrets.access_key }}
        AWS_SECRET_ACCESS_KEY: {{ secrets.secret_key }}

      run: |
        echo $branch 
        terraform init -no-color --backend-config="bucket=${{ secrets.bucket_location }}" -backend-config="key=${{ secrets.state_location}}"
        
        
# ${GITHUB_REF##*/}
# terraform apply -no-color -auto-approve -var
